# Generated by Django 6.0.5 on 2026-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
