# Generated by Django 6.0.6 on 2026-06-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealers', '0002_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('van', 'Van'), ('coupe', 'Coupe'), ('wagon', 'Wagon'), ('bus', 'Bus')], max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('2wd', '2WD'), ('4wd', '4WD'), ('awd', 'AWD')], max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated market / valuation value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the vehicle was bought for — never shown to partners', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='valuation_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='VIN / Chassis number', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Valuation Report, Service History', max_length=100)),
                ('file', models.FileField(upload_to='vehicle_docs/')),
                ('is_partner_visible', models.BooleanField(default=False, help_text='If true, partners can view/download this document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Dealers.vehicle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('repainting', 'Repainting'), ('tyres', 'Tyres'), ('interior_repair', 'Interior Repair'), ('mechanical', 'Mechanical Repair'), ('spare_parts', 'Spare Parts'), ('bulbs', 'Bulbs'), ('bumper_repair', 'Bumper Repair'), ('transport', 'Transport'), ('detailing', 'Detailing'), ('labour', 'Labour'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date_incurred', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Dealers.vehicle')),
            ],
            options={
                'ordering': ['-date_incurred', '-created_at'],
            },
        ),
    ]
